parameters:
    cramtor_payline.merchant_id: ~ # MUST be a string
    cramtor_payline.access_key: ~ # MUST be a string
    cramtor_payline.proxy.host: ~
    cramtor_payline.proxy.port: ~
    cramtor_payline.proxy.login: ~
    cramtor_payline.proxy.password: ~
    cramtor_payline.environment: HOMO
    cramtor_payline.log_verbosity: 200 # Stands for Logger::INFO
    cramtor_payline.default_currency: 978 # ISO code for Euro
    cramtor_payline.default_contract_number: ~ # MUST be a string
    cramtor_payline.default_confirmation_route: ~ # MUST be provided via semantic config
    cramtor_payline.default_error_route: ~ # MUST be provided via semantic config
    cramtor_payline.return_route: cramtor_payline_back_to_shop
    cramtor_payline.cancel_route: cramtor_payline_back_to_shop
    cramtor_payline.notification_route: cramtor_payline_notification

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Set PaylineSDK as a service.
    Payline\PaylineSDK:
        arguments:
            - "%cramtor_payline.merchant_id%"
            - "%cramtor_payline.access_key%"
            - "%cramtor_payline.proxy.host%"
            - "%cramtor_payline.proxy.port%"
            - "%cramtor_payline.proxy.login%"
            - "%cramtor_payline.proxy.password%"
            - "%cramtor_payline.environment%"
            - "%kernel.logs_dir%/"
            - "%cramtor_payline.log_verbosity%"

    cramtor_payline.sdk: '@Payline\PaylineSDK'

    cramtor\PaylineBundle\Payline\Payline:
        $defaultCurrency: "%cramtor_payline.default_currency%"
        $defaultReturnUrl: "@=service('router').generate(parameter('cramtor_payline.return_route'), [], 0)"
        $defaultCancelUrl: "@=service('router').generate(parameter('cramtor_payline.cancel_route'), [], 0)"
        $defaultNotificationUrl: "@=service('router').generate(parameter('cramtor_payline.notification_route'), [], 0)"
        $defaultContractNumber: "%cramtor_payline.default_contract_number%"

    cramtor_payline.gateway: '@cramtor\PaylineBundle\Payline\Payline'
    payline: '@cramtor\PaylineBundle\Payline\Payline'
    cramtor\PaylineBundle\Payline\WebGatewayInterface: '@cramtor\PaylineBundle\Payline\Payline'

    cramtor\PaylineBundle\Controller\PaylineController:
        arguments:
            $defaultConfirmationUrl: "@=service('router').generate(parameter('cramtor_payline.default_confirmation_route'), [], 0)"
            $defaultErrorUrl: "@=service('router').generate(parameter('cramtor_payline.default_error_route'), [], 0)"
        tags:
            - { name: controller.service_arguments }

    cramtor_payline.controller:
        alias: cramtor\PaylineBundle\Controller\PaylineController
        public: true
